image: kasproject/kas:2.0

variables:
  GIT_STRATEGY: clone

.build: &build
  stage: build
  script:
    # define these proxy variables in your CI/CD settings as needed
    - export http_proxy=$HTTP_PROXY
    - export https_proxy=$HTTPS_PROXY
    - export ftp_proxy=$FTP_PROXY
    - export no_proxy=$NO_PROXY
    - cd ..
    - kas build meta-iot2000/$KAS_CONFIG

.build-and-deploy-image: &build-and-deploy-image
  <<: *build
  after_script:
    - for IMAGE in $DEPLOY_IMAGES; do
          xz -c -T0 -9 ../build/tmp/deploy/images/iot2000/$IMAGE > $IMAGE.xz;
      done
  artifacts:
    name: "${CI_JOB_NAME}-${CI_COMMIT_SHA::12}"
    paths:
      - ./*.xz
    expire_in: 1 week

.build-and-deploy-sdk: &build-and-deploy-sdk
  <<: *build
  after_script:
    - mv ../build/tmp/deploy/sdk/$DEPLOY_SDK .
  artifacts:
    name: "${CI_JOB_NAME}-${CI_COMMIT_SHA::12}"
    paths:
      - $DEPLOY_SDK
    expire_in: 1 week

bsp-rt:
  <<: *build-and-deploy-image
  variables:
    KAS_CONFIG: kas-bsp-rt.yml
    DEPLOY_IMAGES: core-image-rt-iot2000.wic

example-image:
  <<: *build-and-deploy-image
  variables:
    KAS_CONFIG: kas-example.yml
    DEPLOY_IMAGES: iot2000-example-image-iot2000.wic

update-image:
#  <<: *build-and-deploy-image
  <<: *build
  variables:
    KAS_CONFIG: kas-example-swupdate.yml
    DEPLOY_IMAGES: iot2000-example-image-swu-iot2000.wic iot2000-update-image-iot2000.swu

windows-sdk:
#  <<: *build-and-deploy-sdk
  <<: *build
  variables:
    KAS_CONFIG: kas-sdk-windows-i586.yml
    DEPLOY_SDK: poky-iot2000-glibc-i686-iot2000-example-image-i586-nlp-32-toolchain-2.2.2.tar.xz
